# Generated by Django 3.2.4 on 2021-06-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_cpu_usage_request_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu_usage',
            old_name='request_type',
            new_name='request_method',
        ),
    ]
